name: Deploy to VPS

on:
  push:
    branches:
      - main  # Cambia a la rama que uses como principal si no es main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/bot-ai
            git pull origin main
            docker compose up -d --build
            docker image prune -f
